jaffle_shop:
  outputs:
    dev:
      type: postgres
      threads: 4
      host: postgres
      port: 5432
      user: postgres
      pass: postgres
      dbname: postgres
      schema: public
  target: dev