jaffle_shop:
  outputs:
    dev:
      type: postgres
      threads: 4
      host: sam-dev.c60fteymrmsg.us-east-1.rds.amazonaws.com
      port: 5432
      user: postgres
      pass: <ask for pw>
      dbname: postgres
      schema: public
  target: dev